# Generated by Django 3.2.6 on 2021-08-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_slug_url', models.CharField(help_text='Choose a url slug name which will binded to this api', max_length=1024)),
                ('service_type', models.IntegerField(choices=[(1, 'AWS'), (2, 'HTTP/s Request')], default=0)),
                ('aws_access_key', models.CharField(max_length=256)),
                ('aws_secret_access_key', models.CharField(max_length=256)),
                ('aws_token', models.CharField(max_length=256)),
                ('aws_host', models.CharField(max_length=256)),
                ('aws_region', models.CharField(max_length=256)),
                ('aws_service', models.CharField(max_length=256)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
