# Generated by Django 3.2.6 on 2021-08-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiservice',
            name='service_endpoint_url',
            field=models.CharField(default='', help_text='URL of the API service to connect into', max_length=1024),
        ),
    ]
