# Generated by Django 3.2.6 on 2021-08-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigw', '0002_apiservice_service_endpoint_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiservice',
            name='cache_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apiservice',
            name='cache_limit',
            field=models.IntegerField(default=0, help_text='Cache rxpiry limit in seconds'),
        ),
        migrations.AlterField(
            model_name='apiservice',
            name='service_slug_url',
            field=models.CharField(help_text='Choose a url slug name which will binded to this api, eg(dbca-locations-data)', max_length=1024),
        ),
        migrations.AlterField(
            model_name='apiservice',
            name='service_type',
            field=models.IntegerField(choices=[(1, 'AWS (AWSRequestsAuth)'), (2, 'HTTP/s Request')], default=0),
        ),
    ]
