# Generated by Django 3.2.6 on 2021-08-30 07:01

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apigw', '0005_auto_20210827_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiservice',
            name='aws_access_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='apiservice',
            name='aws_secret_access_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True),
        ),
    ]
