# Generated by Django 3.2.6 on 2021-08-30 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('apigw', '0006_auto_20210830_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiservice',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='apiservice',
            name='service_slug_url',
            field=models.CharField(help_text='Choose a url slug name which will binded to this api, eg(dbca-locations-data)', max_length=1024, unique=True),
        ),
    ]
