# Generated by Django 3.2.6 on 2021-08-30 09:28

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apigw', '0007_auto_20210830_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiservice',
            name='basic_auth_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apiservice',
            name='basic_auth_password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='apiservice',
            name='basic_auth_username',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', null=True),
        ),
    ]
