# Generated by Django 3.2.6 on 2021-08-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigw', '0013_auto_20210831_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiservicelog',
            name='parameters',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='apiservicelog',
            name='server_ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apiservicelog',
            name='client_ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
