# Generated by Django 3.2.6 on 2021-08-31 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigw', '0014_auto_20210831_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiservicelog',
            old_name='parameters',
            new_name='parameters_get',
        ),
        migrations.AddField(
            model_name='apiservicelog',
            name='parameters_post',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
