# Generated by Django 3.2.6 on 2021-08-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigw', '0015_auto_20210831_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiservicelog',
            name='allowed',
            field=models.BooleanField(default=False),
        ),
    ]
