# Generated by Django 3.2.6 on 2021-08-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigw', '0016_apiservicelog_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiservice',
            name='throttle_limit',
            field=models.IntegerField(default=20, help_text='Query throttle limit per client IP'),
        ),
        migrations.AddField(
            model_name='apiservice',
            name='throttle_period',
            field=models.IntegerField(default=60, help_text='Time limit for throttle limit '),
        ),
        migrations.AddField(
            model_name='apiservice',
            name='throttling_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
