# Generated by Django 3.2.6 on 2021-08-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigw', '0017_auto_20210831_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiservice',
            name='throttle_limit',
            field=models.IntegerField(default=20, help_text='Query throttle limit per client IP (Request Count)'),
        ),
        migrations.AlterField(
            model_name='apiservice',
            name='throttle_period',
            field=models.IntegerField(default=60, help_text='Time limit for throttle limit (in seconds) '),
        ),
    ]
