# Generated by Django 3.2.6 on 2021-08-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigw', '0018_auto_20210831_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiservicelog',
            name='error',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
